project_id = "dggmyssboghmwytvuuqq"

[functions.chat-assistant]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.slack-oauth]
verify_jwt = false

[functions.jira-oauth-callback]
verify_jwt = false