project_id = "dggmyssboghmwytvuuqq"

[functions.chat-assistant]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.slack-oauth-start]
verify_jwt = true

[functions.slack-oauth-callback]
verify_jwt = false

[functions.slack-sync]
verify_jwt = false

[functions.slack-messages]
verify_jwt = true